language: java
before_script:
- echo "Starting building"
script:
- mvn clean package
after_script:
- echo "Script finished"
after_success:
- echo "Build ready"
after_failure:
- echo "Build failure"
- env